---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: skyway-database
  namespace: argocd
spec:
  destination:
    namespace: skyway
    server: https://kubernetes.default.svc
  project: default
  source:
    path: kustomize/overlays/docker-desktop
    repoURL: https://github.com/jayamorin/skyway-database.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
