---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world
  namespace: argocd
spec:
  destination:
    namespace: hello-world
    server: https://kubernetes.default.svc
  project: default
  source:
    path: kustomize/overlays/docker-desktop
    repoURL: https://github.com/jayamorin/hello-world.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true`
