---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
#commonLabels:
#  app.kubernetes.io/part-of: management
#  app.kubernetes.io/managed-by: kustomize
resources:
- ../../base
- ingressroute.yaml
#- middleware.yaml
patches:
- path: argocd-cmd-params-cm-patch.yaml
- path: argocd-server-service-patch.yaml
