---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
#commonLabels:
#  app.kubernetes.io/part-of: management
#  app.kubernetes.io/managed-by: kustomize
namespace: argocd
resources:
  - namespace.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.6.8/manifests/ha/install.yaml

